name: build

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        targets: ["win-x64", "linux-x64", "linux-arm", "linux-arm64"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22.12.0

      - name: Build with dotnet
        run: |
          dotnet publish TS3AudioBot -c Release --framework netcoreapp3.1 --self-contained --runtime ${{ matrix.targets }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TS3AudioBot_${{ matrix.targets }}
          path: |
            TS3AudioBot/bin/Release/netcoreapp3.1/${{ matrix.targets }}/publish
